# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9260691de2fd6b60befc44b32ba6c26a150d8f4cd945075eb65493608b14b7cf441287faa57a3e43aa35bfaa0e2ca46cfd8955ad35177e90465591c2aa103858

test:
  secret_key_base: d47114abc20753179bbd4aaa3e5b1f1c6d67e838b51eedd5a75a50a422010adad3d5e9e94596f177d50c7f6c575555a8cf7a594233c2efcdcb184d49adbdb934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
